name: OnePercent
options:
  bundleIdPrefix: com.blakemartin.onepercent
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  OnePercent:
    type: application
    platform: iOS
    sources:
      - path: OnePercent
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: SharedKit
      - target: OnePercentKeyboard
        embed: true
        codeSign: true
      - target: OnePercentShare
        embed: true
        codeSign: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blakemartin.onepercent.app
        INFOPLIST_FILE: OnePercent/Info.plist
        CODE_SIGN_ENTITLEMENTS: OnePercent/OnePercent.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: OnePercent/Info.plist
      properties:
        CFBundleDisplayName: OnePercent
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        CFBundleURLTypes:
          - CFBundleURLName: com.blakemartin.onepercent.app
            CFBundleURLSchemes:
              - onepercent
        NSPhotoLibraryUsageDescription: "OnePercent needs access to your photos to import dating profile screenshots."
        UIBackgroundModes: []
    entitlements:
      path: OnePercent/OnePercent.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.blakemartin.onepercent.app
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.blakemartin.onepercent.shared

  OnePercentKeyboard:
    type: app-extension
    platform: iOS
    sources:
      - path: OnePercentKeyboard
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: SharedKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blakemartin.onepercent.app.keyboard
        INFOPLIST_FILE: OnePercentKeyboard/Info.plist
        CODE_SIGN_ENTITLEMENTS: OnePercentKeyboard/OnePercentKeyboard.entitlements
        SKIP_INSTALL: YES
    info:
      path: OnePercentKeyboard/Info.plist
      properties:
        CFBundleDisplayName: OnePercent
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: en-US
            RequestsOpenAccess: true
          NSExtensionPointIdentifier: com.apple.keyboard-service
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).KeyboardViewController
    entitlements:
      path: OnePercentKeyboard/OnePercentKeyboard.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.blakemartin.onepercent.app
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.blakemartin.onepercent.shared

  OnePercentShare:
    type: app-extension
    platform: iOS
    sources:
      - path: OnePercentShare
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: SharedKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blakemartin.onepercent.app.share
        INFOPLIST_FILE: OnePercentShare/Info.plist
        CODE_SIGN_ENTITLEMENTS: OnePercentShare/OnePercentShare.entitlements
        SKIP_INSTALL: YES
    info:
      path: OnePercentShare/Info.plist
      properties:
        CFBundleDisplayName: Import to OnePercent
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsImageWithMaxCount: 10
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
    entitlements:
      path: OnePercentShare/OnePercentShare.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.blakemartin.onepercent.app

packages:
  SharedKit:
    path: Shared

schemes:
  OnePercent:
    build:
      targets:
        OnePercent: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
